# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 611f143971b47acfcd224575b09adb078eaf6a7f1e8998182c36c0a1d1ad159e55c3c1604a42a9498cff2db2ec72584177524492053220ab9aac0c15709cfaa8

test:
  secret_key_base: c76340f18d93f17ae8deb11fec4acc2af450e6fa795a6a421526ea4d55ed3c49aa8b368130beda8cedeb72ef1ad61c1f6513255bf869eadc0cf2400dbd056d9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
